"""Ajout MessageContact et Abonne

Revision ID: 803cf7833b03
Revises: 345302e93b80
Create Date: 2026-02-23 17:00:25.647736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803cf7833b03'
down_revision = '345302e93b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date_inscription', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('messages_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('objet', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=True),
    sa.Column('lu', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_contact')
    op.drop_table('abonnes')
    # ### end Alembic commands ###
