"""Ajout colonnes manquantes et tables photos videos

Revision ID: ab97092fe836
Revises: 803cf7833b03
Create Date: 2026-02-23 19:02:39.837407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab97092fe836'
down_revision = '803cf7833b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.Column('publie', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url_video', sa.String(length=500), nullable=False),
    sa.Column('miniature_url', sa.String(length=500), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.Column('publie', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actualites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie', sa.String(length=100), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taille_fichier', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('telechargements', sa.Integer(), nullable=True))

    with op.batch_alter_table('evenements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie', sa.String(length=100), nullable=True))

    with op.batch_alter_table('partenaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordre', sa.Integer(), nullable=True))

    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projets', schema=None) as batch_op:
        batch_op.drop_column('budget')
        batch_op.drop_column('categorie')

    with op.batch_alter_table('partenaires', schema=None) as batch_op:
        batch_op.drop_column('ordre')

    with op.batch_alter_table('evenements', schema=None) as batch_op:
        batch_op.drop_column('categorie')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('telechargements')
        batch_op.drop_column('taille_fichier')

    with op.batch_alter_table('actualites', schema=None) as batch_op:
        batch_op.drop_column('categorie')

    op.drop_table('videos')
    op.drop_table('photos')
    # ### end Alembic commands ###
